// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@hwwach.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение всех assets авторизованного пользователя (без вложений)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Список assets пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создание нового asset в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Создать asset",
                "parameters": [
                    {
                        "description": "Данные asset",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/assets/change-requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Получить список всех заявок со статусом pending (для администратора)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-change-requests"
                ],
                "summary": "Список всех заявок (Admin only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AssetChangeRequestResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/assets/change-requests/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin only. Администратор меняет статус заявки и применяет её (если approved)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-change-requests"
                ],
                "summary": "Одобрить/отклонить заявку (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID заявки (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус и комментарий",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ApproveChangeRequestInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение информации об asset по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Получить asset по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID asset (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Asset"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Частичное обновление asset, если он еще не проверен администратором",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Редактировать asset (до проверки)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID asset (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/assets/{id}/change-requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Пользователь создает заявку на редактирование или удаление своего актива",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "asset-change-requests"
                ],
                "summary": "Создать заявку на изменение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID актива (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные заявки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateChangeRequestInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AssetChangeRequestCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/assets/{id}/photos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение всех фотографий для указанного asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Список фотографий asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID asset (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Photo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/photos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение всех фотографий авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photos"
                ],
                "summary": "Список фотографий сделанных пользователем",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/photos/complete-upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменение статуса фотографии на completed после успешной загрузки в MinIO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photos"
                ],
                "summary": "Подтвердить загрузку фотографии",
                "parameters": [
                    {
                        "description": "UUID фотографии и опционально устройство",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConfirmUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PhotoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/photos/upload-url": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает временный URL для прямой загрузки файла в MinIO (минуя сервер). Макс. размер файла: 20 МБ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photos"
                ],
                "summary": "Получить presigned URL для загрузки фотографии",
                "parameters": [
                    {
                        "description": "Имя файла, MIME тип и размер",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UploadPhotoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadPhotoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/photos/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаление фотографии по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photos"
                ],
                "summary": "Удалить фотографию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID фотографии (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создание нового запроса в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Создать запрос",
                "parameters": [
                    {
                        "description": "Данные запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Request"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/requests/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение информации о запросе по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Получить запрос по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID запроса (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Request"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаление запроса по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Удалить запрос",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID запроса (uuid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ApproveChangeRequestInput": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "admin_comment": {
                    "type": "string",
                    "example": "Изменения приняты"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected"
                    ],
                    "example": "approved"
                }
            }
        },
        "dto.AssetChangeRequestCreatedResponse": {
            "type": "object",
            "properties": {
                "asset_uuid": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "client_id": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "uuid": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                }
            }
        },
        "dto.AssetChangeRequestResponse": {
            "type": "object",
            "properties": {
                "admin_comment": {
                    "type": "string"
                },
                "asset_uuid": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "client_id": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "created_at": {
                    "type": "string"
                },
                "proposed_data": {
                    "type": "object"
                },
                "reason": {
                    "type": "string",
                    "example": "Неверно указан тип"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "type": {
                    "type": "string",
                    "example": "update"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uuid": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                }
            }
        },
        "dto.AssetListResponse": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssetResponse"
                    }
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "dto.AssetResponse": {
            "type": "object",
            "properties": {
                "admin_comment": {
                    "type": "string"
                },
                "asset_status": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "inventory_num": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uuid": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "verified_at": {
                    "type": "string",
                    "example": "2026-05-11T12:00:00Z"
                }
            }
        },
        "dto.ConfirmUploadRequest": {
            "type": "object",
            "required": [
                "photo_uuid"
            ],
            "properties": {
                "asset_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "photo_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.CreateAssetRequest": {
            "type": "object",
            "required": [
                "category",
                "inventory_num",
                "name"
            ],
            "properties": {
                "asset_status": {
                    "type": "string",
                    "example": "active"
                },
                "category": {
                    "type": "string",
                    "example": "ноутбук"
                },
                "client_id": {
                    "description": "UUID сгенерированный клиентом",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "description": {
                    "type": "string",
                    "example": "MacBook Pro 16"
                },
                "inventory_num": {
                    "type": "string",
                    "example": "ИНВ-001"
                },
                "name": {
                    "type": "string",
                    "example": "Ноутбук служебный"
                }
            }
        },
        "dto.CreateChangeRequestInput": {
            "type": "object",
            "required": [
                "reason",
                "type"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "proposed_data": {
                    "type": "object"
                },
                "reason": {
                    "type": "string",
                    "example": "Неверно указан тип"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "update",
                        "delete"
                    ],
                    "example": "update"
                }
            }
        },
        "dto.PhotoListResponse": {
            "type": "object",
            "properties": {
                "photos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PhotoResponse"
                    }
                },
                "user_uuid": {
                    "type": "string"
                }
            }
        },
        "dto.PhotoResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "UUID сгенерированный клиентом (если был передан)",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateAssetRequest": {
            "type": "object",
            "properties": {
                "asset_status": {
                    "type": "string",
                    "example": "inactive"
                },
                "category": {
                    "type": "string",
                    "example": "ноутбук"
                },
                "description": {
                    "type": "string",
                    "example": "MacBook Pro 16 2023"
                },
                "inventory_num": {
                    "type": "string",
                    "example": "ИНВ-002"
                },
                "name": {
                    "type": "string",
                    "example": "Ноутбук служебный"
                }
            }
        },
        "dto.UploadPhotoRequest": {
            "type": "object",
            "required": [
                "file_size",
                "filename"
            ],
            "properties": {
                "client_id": {
                    "description": "UUID сгенерированный клиентом (для оптимистичного UI)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1048576
                },
                "filename": {
                    "type": "string",
                    "example": "photo.jpg"
                }
            }
        },
        "dto.UploadPhotoResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "UUID сгенерированный клиентом",
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "max_file_size": {
                    "description": "Макс. размер файла в байтах",
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "photo_uuid": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "description": "Актив представляет собой физический объект с инвентарным номером",
            "type": "object",
            "properties": {
                "admin_comment": {
                    "description": "Комментарий администратора",
                    "type": "string"
                },
                "asset_status": {
                    "description": "Статус актива",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AssetStatus"
                        }
                    ],
                    "example": "active"
                },
                "category": {
                    "description": "Категория актива",
                    "type": "string"
                },
                "client_id": {
                    "description": "UUID сгенерированный клиентом (для оптимистичного UI)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "Дата удаления (soft delete)",
                    "type": "string"
                },
                "description": {
                    "description": "Описание актива",
                    "type": "string"
                },
                "inventory_num": {
                    "description": "Инвентарный номер",
                    "type": "string"
                },
                "moderation_status": {
                    "$ref": "#/definitions/models.ModerationStatus"
                },
                "name": {
                    "description": "Название актива",
                    "type": "string"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Photo"
                    }
                },
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Request"
                    }
                },
                "updated_at": {
                    "description": "Дата обновления",
                    "type": "string"
                },
                "user_uuid": {
                    "description": "UUID владельца (из auth-сервиса)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uuid": {
                    "description": "UUID актива (v7)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "verified_at": {
                    "description": "Дата верификации админом",
                    "type": "string"
                }
            }
        },
        "models.AssetStatus": {
            "type": "string",
            "enum": [
                "active",
                "inactive",
                "maintenance",
                "repair",
                "decommissioned",
                "lost"
            ],
            "x-enum-comments": {
                "AssetStatusActive": "В эксплуатации",
                "AssetStatusDecommissioned": "Списан",
                "AssetStatusInactive": "Не используется",
                "AssetStatusLost": "Утерян",
                "AssetStatusMaintenance": "На обслуживании",
                "AssetStatusRepair": "В ремонте"
            },
            "x-enum-descriptions": [
                "В эксплуатации",
                "Не используется",
                "На обслуживании",
                "В ремонте",
                "Списан",
                "Утерян"
            ],
            "x-enum-varnames": [
                "AssetStatusActive",
                "AssetStatusInactive",
                "AssetStatusMaintenance",
                "AssetStatusRepair",
                "AssetStatusDecommissioned",
                "AssetStatusLost"
            ]
        },
        "models.ModerationStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected"
            ],
            "x-enum-varnames": [
                "ModerationPending",
                "ModerationApproved",
                "ModerationRejected"
            ]
        },
        "models.Photo": {
            "description": "Фотография загруженная пользователем и привязанная к assets",
            "type": "object",
            "properties": {
                "assets": {
                    "description": "Активы на фото (many-to-many)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Asset"
                    }
                },
                "client_id": {
                    "description": "UUID сгенерированный клиентом (для оптимистичного UI)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                },
                "content_type": {
                    "description": "MIME тип файла",
                    "type": "string",
                    "example": "image/jpeg"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "Дата удаления (soft delete)",
                    "type": "string"
                },
                "file_name": {
                    "description": "Имя файла",
                    "type": "string",
                    "example": "photo.jpg"
                },
                "file_size": {
                    "description": "Размер файла в байтах",
                    "type": "integer",
                    "example": 1048576
                },
                "status": {
                    "description": "Статус загрузки",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PhotoStatus"
                        }
                    ],
                    "example": "pending"
                },
                "updated_at": {
                    "description": "Дата обновления",
                    "type": "string"
                },
                "url": {
                    "description": "Ссылка на фото в MinIO",
                    "type": "string"
                },
                "user_uuid": {
                    "description": "UUID владельца (из auth-сервиса)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uuid": {
                    "description": "UUID фотографии (v7, генерируется сервером)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                }
            }
        },
        "models.PhotoStatus": {
            "type": "string",
            "enum": [
                "pending",
                "completed"
            ],
            "x-enum-comments": {
                "PhotoStatusCompleted": "Загрузка завершена",
                "PhotoStatusPending": "Ожидает загрузки (выдан presigned URL)"
            },
            "x-enum-descriptions": [
                "Ожидает загрузки (выдан presigned URL)",
                "Загрузка завершена"
            ],
            "x-enum-varnames": [
                "PhotoStatusPending",
                "PhotoStatusCompleted"
            ]
        },
        "models.Request": {
            "description": "Запрос создаётся пользователем для обслуживания или ремонта устройства",
            "type": "object",
            "properties": {
                "asset": {
                    "description": "Актив (FK)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Asset"
                        }
                    ]
                },
                "asset_uuid": {
                    "description": "UUID актива",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "created_at": {
                    "description": "Дата создания",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "Дата удаления (soft delete)",
                    "type": "string"
                },
                "message": {
                    "description": "Текст запроса",
                    "type": "string"
                },
                "photo_url": {
                    "description": "Ссылка на фото (опционально)",
                    "type": "string"
                },
                "status": {
                    "description": "Статус запроса",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Дата обновления",
                    "type": "string"
                },
                "user_uuid": {
                    "description": "UUID владельца (из auth-сервиса)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "uuid": {
                    "description": "UUID запроса (v7)",
                    "type": "string",
                    "example": "0194f7b0-1234-7xxx-xxxx-xxxxxxxxxxxx"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите JWT токен в формате \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HwWach API",
	Description:      "API для управления активами и фотографиями",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
